# Generated by Django 5.0.7 on 2024-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Default City', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='num_bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='num_floors',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.IntegerField(default=100),
        ),
    ]
