# Generated by Django 5.0.7 on 2024-07-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Default City', max_length=50),
            preserve_default=False,
        ),
    ]
