# Generated by Django 5.0.7 on 2024-07-21 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='num_bedrooms',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='num_floors',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.IntegerField(default='100'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Default City', max_length=50),
        ),
    ]
