# Generated by Django 5.0.7 on 2024-07-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_property_num_bedrooms_property_num_floors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='num_floors',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='square_feet',
            field=models.IntegerField(default='100'),
        ),
    ]
