# Generated by Django 5.0.7 on 2024-07-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_property_num_floors_alter_property_square_feet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='num_bedrooms',
            field=models.IntegerField(default=1),
        ),
    ]
