# Generated by Django 5.0.7 on 2024-07-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_property_additional_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='additional_files',
        ),
    ]
