# Generated by Django 5.0.7 on 2024-07-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_property_num_bedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='num_bedrooms',
        ),
    ]
