# Generated by Django 5.0.7 on 2024-07-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_property_agent'),
    ]

    operations = [
    ]
