# Generated by Django 5.0.7 on 2024-07-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_property_num_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='num_bedrooms',
            field=models.IntegerField(default=1),
        ),
    ]
